### ISSUE TITLE
Issue with make

### ISSUE THREAD

**Issue by akesm** [floquation/OF-kva_interfaceProperties#1]
I tried wmake, but I got an error about missing of labelSpecific.H 
So one needs to first do wclean then wmake, because on OF 4.1 seems that that headerfile does not anymore exist :)

**Comment by floquation** [comment]
Seems like I committed a compiled version for OF4.0. That's why you ran into that problem when compiling it for OF4.1. I'll get rid of the Make/linux(...) folder and that issue should be resolved permanently.
